config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	enum status: {submitted: 0, approved: 1, rejected: 2}
	belongs_to :user
	validates_presence_of :date, :rational
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
  	last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))

        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index 
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save 
			redirect_to @post, notice: "Post was created successfully!"
		else
			render :new
		end
	end

	def show
		
	end

	def edit
		authorize @post
	end

	def update
		authorize @post
		if @post.update(post_params)
			redirect_to @post, notice: "Post updated successfully!"
		else
			render :edit
		end
	end

	def destroy
		@post.delete
		redirect_to posts_path, notice: "Post was deleted!"
	end

	private

	def post_params
		params.require(:post).permit(:date,:rational,:status)
	end
	def set_post
		@post = Post.find(params[:id]) 
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	
	def homepage
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(page)
		"active" if current_page?(page)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<%= render 'shared/nav'%>
    			<%= yield %>
			</div>
		</div>
	</div>
  <%= js add_gritter(flash[:notice],:title => "Overtime notification.", :sticky => true,:time => 1000) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |error|%>			
			<%= js add_gritter(error,:title => error, :sticky => true) %>
		<% end %>
	<% end %>
	<div class='form-group'>
  		<%= f.date_field :date, class: "form-control" %>
 	</div>
   <div class="form-group">
   		<%= f.text_area :rational,class: "form-control" %>
   	</div>
   <%= render partial: 'status', locals: {f: f} if current_user.type == 'AdminUser' %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<tr>
	<td><%= post.id %></td>
	<td><%= post.date %></td>
	<td><%= truncate post.rational %></td>
	<td><%= post.user.full_name %></td>
	<td><%= link_to "Edit", edit_post_path(post), id: "edit_#{post.id}" %></td>
	<td><%= link_to "Delete", post_path(post), method: :delete,id: "delete_post_#{post.id}_from_index", data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/posts/_status.html.erb
  	   <div class="form-group">
   	   	<%= f.radio_button :status, "submitted" %>
   		<%= f.label :status, "Submited" %>
   		
   	</div>
   	<div class="form-group">
   		<%= f.radio_button :status, "approved" %>
   		<%= f.label :status, "Approved" %>
   		
   	</div>
   	<div class="form-group">
   		<%= f.radio_button :status, "rejected" %>
   		<%= f.label :status, "Rejected" %>
   		
   	</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Posts
			</th>
			<th>
				Rationale
			</th>
			<th>
				Name
			</th>
			<th>Edit</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<%= render @posts %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.rational%>

app/views/shared/_nav.html.erb
<div class="logo">
	<h1>Tracker</h1>
</div>

<% if current_user %>
<ul class="custom-nav nav nav-tabs">
	<li class="<%= active?(root_path)%>">
		<%= link_to "Home", root_path %>
	</li>
	<li class="<%= active?(posts_path)%>">
		<%= link_to "Time entries", posts_path %>
	</li>
	<li class="<%= active?(new_post_path)%>">
		<%= link_to "Add new entry", new_post_path, id: "new_post_from_nav" %>
	</li>
	<li class="nav-item dropdown ml-md-auto pull-right">
		 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">	
				<% if current_user.try(:type) == 'AdminUser' %>
			 	<%= link_to "TODO: Admin", admin_root_path ,class: "dropdown-item" %>
			 	<% end %>
			<div class="dropdown-divider">
			<%= link_to "Logout", destroy_user_session_path, method: :delete,class: "dropdown-item" %>
		</div>
	</li>
</ul>
<% end %>